name: CI 2.7
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  CI_27:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/cargo@v1
    - uses: actions/setup-ruby@v1.0.0
      with:
        version: 2.7

    - run: cd $GITHUB_WORKSPACE && make
    - run: cd $GITHUB_WORKSPACE && make lint
    - run: cd $GITHUB_WORKSPACE && ./script/test.sh
